chore:setup_db_model
DevKor-github/OnTime-front pull request #14
Opened 2024-10-27 11:47 UTC by SeoHyeonSim

2024-10-28 09:29 UTC, jjoonleo commented on lib/data/daos/place_dao.dart
> +  Future<List> getAllPlaces() async {
type을 Future<List<PlaceEntity>>로 해주시면 좋을 것 같습니다.

2024-10-28 09:36 UTC, jjoonleo commented on lib/data/daos/schedule_dao.dart
> +  Future<void> createPlace(PlaceEntity placeEntity) async {
이 두 함수는 각각 해당하는 dao에 위치하는 것이 더 좋을 것 같습니다.

2024-10-30 05:49 UTC, jjoonleo requested changes
댓글에 수정하면 좋을 것 같은 부분 남겨뒀습니다.

2024-10-31 00:32 UTC, SeoHyeonSim commented
리뷰하신 내용 바탕으로 수정했습니다! 
다만 바꾸는 과정에서 구조가 변경된 이후 database.g.dart에서 
 late final ScheduleDao scheduleDao = ScheduleDao(this as AppDatabase); 

이 부분에 인자가 1개만 전송되는 오류가 발생하고 있습니다. 
schedule_dao.dart랑 database.dat 파일에서 계속 전달 인자 초기화 설정하면서 수정해보려 하고 있는데, 좀처럼 오류가 해결이 안되네요;;  build시에 계속 해당 오류가 발생하는 g.dart가 생성이 되는 상태입니다. 
우선 브랜치에 업데이트 해 놓겠습니다. 혹시 해당 오류에 대해서 어떻게 수정하면 좋을 지 아시면 알려주세요...!

2024-10-31 05:05 UTC, closed without merging