47 implement preparationremotedatasource
DevKor-github/OnTime-front pull request #70
Opened 2024-12-14 15:44 UTC by SeoHyeonSim

## Describe your changes
- Implement PreparationRemoteDataSource
- Create test for PreparationRemoteDataSource
- Create usecases

2024-12-22 08:04 UTC, jjoonleo requested changes

2024-12-22 08:04 UTC, jjoonleo commented on lib/data/data_sources/preparation_remote_data_source.dart
> +      PreparationEntity preparationEntity, String userId) async {
userId 파라메터는 사용이 안되는 상황이라면 없어도 괜찮을 것 같습니다.

2024-12-22 13:44 UTC, jjoonleo approved these changes

2024-12-22 13:44 UTC, jjoonleo submitted a review, later dismissed

2024-12-22 19:13 UTC, jjoonleo commented on .vscode/settings.json
이부부은 merge가 안된건가요?

2024-12-23 02:01 UTC, SeoHyeonSim commented on .vscode/settings.json
브랜치 문제 수정하다가 섞여 들어간 모양이네요. 수정했습니다!

2024-12-30 08:43 UTC, jjoonleo submitted a review, later dismissed

2025-01-03 04:35 UTC, jjoonleo submitted a review, later dismissed

2025-01-03 05:27 UTC, jjoonleo approved these changes

2025-01-03 07:10 UTC, merged